### PR TITLE
Import the league schedule

### LINKED ISSUE #777: Schedule the league matches
The schedule for the league matches needs to be generated.

### Original

[comp/game/league-schedule](https://github.com/srobo/recurring-tasks/blob/master/comp/game/league-schedule.yaml)

### PR DESCRIPTION
**Pull request by PeterJCLaw**
Fixes https://github.com/srobo/tasks/issues/777

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
This import currently has 12 appearances per team and completely fills the available time. @prophile how many rounds do we want?

**Comment by sedders123** [comment]
The validate action has the following warning

```
Schedule  has the following errors:
    Only contains enough time for 85 matches, 91 are planned
```

**Comment by PeterJCLaw** [comment]
Indeed, discussion is happening in https://studentrobotics.slack.com/archives/C3190DWP3/p1650393403016129

**Comment by PeterJCLaw** [comment]
Summary of ratings:
<details>
<summary>Closeness</summary>

```
$ ../league-checker/checks/close.py t26r6x2redbb.txt 
Team	Min-gap	Count	Gaps
25	5	4	[26, 6, 8, 8, 5, 7, 12, 5, 5, 7, 5, 7]
16	5	2	[26, 7, 6, 5, 9, 8, 5, 7, 8, 8, 7, 7]
8	5	2	[26, 5, 8, 6, 7, 8, 6, 8, 5, 7, 8, 6]
3	5	1	[26, 8, 7, 6, 9, 7, 6, 6, 9, 6, 7, 5]
11	5	5	[27, 8, 5, 6, 13, 5, 6, 7, 5, 5, 7, 5]
24	5	3	[27, 6, 7, 7, 7, 6, 5, 8, 7, 8, 5, 5]
13	5	5	[27, 7, 5, 7, 6, 5, 12, 5, 5, 5, 7, 8]
26	5	3	[27, 5, 9, 5, 6, 6, 9, 7, 9, 6, 9, 5]
1	5	3	[28, 6, 8, 5, 9, 6, 6, 7, 5, 5, 6, 7]
5	5	3	[28, 5, 6, 8, 10, 5, 8, 6, 6, 6, 5, 8]
10	5	3	[28, 7, 6, 8, 9, 6, 5, 7, 5, 7, 8, 5]
6	5	3	[28, 8, 6, 8, 5, 5, 5, 6, 8, 6, 10, 8]
23	5	3	[29, 7, 7, 8, 6, 7, 7, 5, 7, 5, 5, 7]
7	5	3	[29, 8, 5, 6, 6, 5, 6, 5, 8, 6, 8, 7]
2	5	6	[29, 5, 11, 5, 5, 8, 8, 6, 5, 8, 5, 5]
19	5	3	[29, 6, 6, 7, 5, 5, 9, 5, 7, 8, 7, 8]
20	5	3	[30, 8, 8, 5, 7, 5, 5, 6, 6, 6, 6, 8]
18	5	4	[30, 5, 5, 5, 7, 7, 8, 8, 8, 7, 5, 7]
12	5	3	[30, 6, 6, 7, 5, 7, 5, 6, 6, 8, 5, 6]
15	5	3	[30, 7, 7, 7, 5, 8, 6, 5, 5, 7, 6, 6]
9	5	5	[31, 5, 7, 7, 7, 6, 5, 5, 5, 7, 6, 5]
21	5	4	[31, 7, 5, 5, 5, 6, 6, 7, 12, 5, 8, 6]
14	5	4	[31, 6, 8, 6, 5, 5, 8, 8, 8, 5, 5, 6]
22	5	5	[32, 5, 7, 5, 6, 7, 5, 6, 8, 6, 5, 5]
17	5	4	[32, 6, 6, 6, 5, 6, 5, 5, 7, 5, 9, 6]
4	5	5	[33, 5, 5, 6, 5, 8, 6, 8, 5, 5, 10, 6]

0 teams have a minimum gap of 2
```

</details>

<details>
<summary>Corners</summary>

```
$ ../league-checker/checks/corners.py t26r6x2redbb.txt 
 Team |  Std. Dev. | Corner Counts
   8  |   0.707    |  3  3  4  2
   5  |   0.707    |  3  4  2  3
  25  |   0.707    |  3  2  3  4
   9  |   0.000    |  3  3  3  3
   7  |   0.000    |  3  3  3  3
   6  |   0.000    |  3  3  3  3
   4  |   0.000    |  3  3  3  3
   3  |   0.000    |  3  3  3  3
  26  |   0.000    |  3  3  3  3
  24  |   0.000    |  3  3  3  3
  23  |   0.000    |  3  3  3  3
  22  |   0.000    |  3  3  3  3
  21  |   0.000    |  3  3  3  3
  20  |   0.000    |  3  3  3  3
   2  |   0.000    |  3  3  3  3
  19  |   0.000    |  3  3  3  3
  18  |   0.000    |  3  3  3  3
  17  |   0.000    |  3  3  3  3
  16  |   0.000    |  3  3  3  3
  15  |   0.000    |  3  3  3  3
  14  |   0.000    |  3  3  3  3
  13  |   0.000    |  3  3  3  3
  12  |   0.000    |  3  3  3  3
  11  |   0.000    |  3  3  3  3
  10  |   0.000    |  3  3  3  3
   1  |   0.000    |  3  3  3  3
```

</details>

<details>
<summary>Faced</summary>

```
$ ../league-checker/checks/faced.py t26r6x2redbb.txt 
25   faces 18, misses  7, repeats  3 more than 3 times
16   faces 18, misses  7, repeats  0 more than 3 times
8    faces 20, misses  5, repeats  1 more than 3 times
3    faces 21, misses  4, repeats  1 more than 3 times
11   faces 17, misses  8, repeats  2 more than 3 times
24   faces 22, misses  3, repeats  1 more than 3 times
13   faces 21, misses  4, repeats  2 more than 3 times
26   faces 17, misses  8, repeats  1 more than 3 times
1    faces 18, misses  7, repeats  1 more than 3 times
5    faces 18, misses  7, repeats  3 more than 3 times
10   faces 20, misses  5, repeats  2 more than 3 times
6    faces 20, misses  5, repeats  1 more than 3 times
23   faces 20, misses  5, repeats  1 more than 3 times
7    faces 21, misses  4, repeats  1 more than 3 times
2    faces 17, misses  8, repeats  2 more than 3 times
19   faces 19, misses  6, repeats  1 more than 3 times
20   faces 21, misses  4, repeats  0 more than 3 times
18   faces 22, misses  3, repeats  0 more than 3 times
12   faces 21, misses  4, repeats  0 more than 3 times
15   faces 17, misses  8, repeats  1 more than 3 times
9    faces 19, misses  6, repeats  0 more than 3 times
21   faces 20, misses  5, repeats  2 more than 3 times
14   faces 21, misses  4, repeats  1 more than 3 times
22   faces 22, misses  3, repeats  1 more than 3 times
17   faces 19, misses  6, repeats  1 more than 3 times
4    faces 17, misses  8, repeats  1 more than 3 times
```

</details>

<details>
<summary>Matches Per Team</summary>

```
$ ../league-checker/checks/matches-per-team.py t26r6x2redbb.txt 
25: 12
16: 12
8: 12
3: 12
11: 12
24: 12
13: 12
26: 12
1: 12
5: 12
10: 12
6: 12
23: 12
7: 12
2: 12
19: 12
20: 12
18: 12
12: 12
15: 12
9: 12
21: 12
14: 12
22: 12
17: 12
4: 12
```

</details>

<details>
<summary>Overlaps</summary>

```
$ ../league-checker/checks/overlaps.py t26r6x2redbb.txt 
Match 1 overlaps with match 20: 11,13,24,26 vs 11,13,20,26
Match 15 overlaps with match 32: 10,19,26,3 vs 10,19,20,26
Match 19 overlaps with match 64: 14,18,2,8 vs 14,18,2,3
Match 19 overlaps with match 69: 14,18,2,8 vs 14,18,2,6
Match 20 overlaps with match 48: 11,13,20,26 vs 13,20,26,8
Match 22 overlaps with match 27: 19,21,25,7 vs 16,19,21,25
Match 22 overlaps with match 46: 19,21,25,7 vs 12,19,21,25
Match 23 overlaps with match 55: 10,12,22,4 vs 10,16,22,4
Match 24 overlaps with match 29: 17,2,6,9 vs 17,2,22,6
Match 24 overlaps with match 45: 17,2,6,9 vs 17,2,23,6
Match 26 overlaps with match 48: 13,18,26,8 vs 13,20,26,8
Match 27 overlaps with match 46: 16,19,21,25 vs 12,19,21,25
Match 27 overlaps with match 63: 16,19,21,25 vs 16,21,25,26
Match 29 overlaps with match 45: 17,2,22,6 vs 17,2,23,6
Match 30 overlaps with match 49: 1,14,15,3 vs 1,15,18,3
Match 35 overlaps with match 40: 12,14,16,17 vs 12,16,17,8
Match 44 overlaps with match 73: 11,15,5,7 vs 11,13,15,7
Match 50 overlaps with match 62: 10,23,4,5 vs 10,23,24,5
Match 51 overlaps with match 56: 11,14,2,25 vs 11,2,25,5
Match 55 overlaps with match 70: 10,16,22,4 vs 10,16,4,9
Match 62 overlaps with match 67: 10,23,24,5 vs 15,23,24,5
Match 63 overlaps with match 77: 16,21,25,26 vs 16,21,26,6
Match 64 overlaps with match 69: 14,18,2,3 vs 14,18,2,6
```

</details>

**Pull request merged**
