### PR TITLE
Add a compact 24-team knockouts schedule

### LINKED ISSUE #776: Design the SR2022 knockouts
We need to specify the structure of the knockouts.

### Original

[comp/game/knockout-design](https://github.com/srobo/recurring-tasks/blob/master/comp/game/knockout-design.yaml)

### PR DESCRIPTION
**Pull request by PeterJCLaw**
Matches from Slack:
https://studentrobotics.slack.com/archives/C3190DWP3/p1650796912860359?thread_ts=1650793235.360159&cid=C3190DWP3

Please do check that I've transcribed the entrants correctly!

Fixes https://github.com/srobo/tasks/issues/776

### CODE REVIEW

**Review by prophile — APPROVED** [review]
Approved assuming you've done some basic sanity checking

**Comment by PeterJCLaw** [comment]
I've eyeballed the resulting schedule, mostly using the `/comp/knockouts` page on the competition-website. That's about it.
The timings are stolen from the automatic schedule, minus the four at the start this doesn't need.

**Comment by PeterJCLaw** [comment]
For clarity though: I _haven't_ tried populating the matches to check who progresses.

**Comment by PeterJCLaw** [comment]
I've also been through the knockouts with fake scores to check that the right teams progress.

**Pull request merged**
